version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    restart: unless-stopped
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks: 
      - dnasport
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash
    hostname: logstash
    restart: unless-stopped
    links: 
      - elasticsearch
    depends_on: 
      - elasticsearch
    ports:
      - 5044:5044/tcp
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
    networks:
      - dnasport
    environment: 
      XPACK_SECURITY_ENABLED: 'false' 
      XPACK_REPORTING_ENABLED: 'false' 
      XPACK_MONITORING_ENABLED: 'false' 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    hostname: kibana
    restart: unless-stopped
    links: 
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    expose: 
      - 5601
    networks: 
      - dnasport
networks:
  dnasport:
    driver: bridge
volumes:
  elasticsearch_data:
    external: false